"""create pokemon type and ability

Revision ID: 0674254ac495
Revises: f468085379df
Create Date: 2025-04-24 09:45:30.631752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0674254ac495'
down_revision: Union[str, None] = 'f468085379df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pokemon_abilities = op.create_table('pokemon_abilities',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'ability_id', 'slot')
    )
    pokemon_types = op.create_table('pokemon_types',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id')
    )

    from migration.tool import load_csv

    with load_csv("pokemon_abilities") as csv_data:
        # pokemon_id,ability_id,is_hidden,slot
        data = [
            {
                "pokemon_id": int(row["pokemon_id"]),
                "ability_id": int(row["ability_id"]),
                "is_hidden": bool(int(row["is_hidden"])),
                "slot": int(row["slot"])
            }
            for row in csv_data
        ]
        op.bulk_insert(pokemon_abilities, data)

    with load_csv("pokemon_types") as csv_data:
        # pokemon_id,type_id,slot
        data = [
            {
                "pokemon_id": int(row["pokemon_id"]),
                "type_id": int(row["type_id"]),
                "slot": int(row["slot"])
            }
            for row in csv_data
        ]
        op.bulk_insert(pokemon_types, data)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_types')
    op.drop_table('pokemon_abilities')
    # ### end Alembic commands ###
