"""create move-damage-class

Revision ID: 5d8b9dd8865f
Revises: 630f311ad9ac
Create Date: 2025-04-22 21:00:30.418798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8b9dd8865f'
down_revision: Union[str, None] = '630f311ad9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    move_damage_classes = op.create_table('move_damage_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    move_damage_class_prose = op.create_table('move_damage_class_prose',
    sa.Column('move_damage_class_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['move_damage_class_id'], ['move_damage_classes.id'], ),
    sa.PrimaryKeyConstraint('move_damage_class_id', 'local_language_id')
    )

    op.bulk_insert(move_damage_classes,[
        { "id": 1, "identifier": "status"},
        { "id": 2, "identifier": "physical"},
        { "id": 3, "identifier": "special"},
    ])

    op.bulk_insert(move_damage_class_prose,[
        { "move_damage_class_id": 1, "local_language_id": 1, "name": "へんか", "description": "ダメージない"},
        { "move_damage_class_id": 1, "local_language_id": 4, "name": "變化", "description": "沒有傷害"},
        { "move_damage_class_id": 1, "local_language_id": 5, "name": "statut", "description": "Aucun dégât"},
        { "move_damage_class_id": 1, "local_language_id": 6, "name": "status", "description": "Kein Schaden"},
        { "move_damage_class_id": 1, "local_language_id": 7, "name": "estado", "description": "Sin Daño"},
        { "move_damage_class_id": 1, "local_language_id": 9, "name": "status", "description": "No damage"},
        { "move_damage_class_id": 1, "local_language_id": 12, "name": "变化", "description": "没有伤害"},

        { "move_damage_class_id": 2, "local_language_id": 1, "name": "ぶつり", "description": "ぶつりのダメージ。こうげきとぼうぎょを行使する"},
        { "move_damage_class_id": 2, "local_language_id": 4, "name": "物理", "description": "物理傷害，受攻擊和防禦影響"},
        { "move_damage_class_id": 2, "local_language_id": 5, "name": "physique", "description": "Dégâts physique, influencés par l'Attaque et la Défense"},
        { "move_damage_class_id": 2, "local_language_id": 6, "name": "physisch", "description": "Physischer Schaden, beeinflusst von Angriff und Verteidigung"},
        { "move_damage_class_id": 2, "local_language_id": 7, "name": "físico", "description": "Daño Físico, controlado por el Ataque y Defensa"},
        { "move_damage_class_id": 2, "local_language_id": 9, "name": "physical", "description": "Physical damage, controlled by Attack and Defense"},
        { "move_damage_class_id": 2, "local_language_id": 12, "name": "物理", "description": "物理伤害，受攻击和防御影响"},

        { "move_damage_class_id": 3, "local_language_id": 1, "name": "とくしゅ", "description": "とくしゅのダメージ。とくこうととくぼうを行使する"},
        { "move_damage_class_id": 3, "local_language_id": 4, "name": "特殊", "description": "特殊傷害，受特攻和特防影響"},
        { "move_damage_class_id": 3, "local_language_id": 5, "name": "spéciale", "description": "Dégâts spéciaux, influencés par l'Attaque Spéciale et la Défense Spéciale"},
        { "move_damage_class_id": 3, "local_language_id": 6, "name": "spezial", "description": "Spezieller Schaden, beeinflusst von Spezialangriff und Spezialverteidigung"},
        { "move_damage_class_id": 3, "local_language_id": 7, "name": "especial", "description": "Daño Especial, controlado por el Ataque Esecieal y Defensa Especial"},
        { "move_damage_class_id": 3, "local_language_id": 9, "name": "special", "description": "Special damage, controlled by Special Attack and Special Defense"},
        { "move_damage_class_id": 3, "local_language_id": 12, "name": "特殊", "description": "特殊伤害，受特攻和特防影响"},
    ])

    # ### end Alembic commands ###




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_damage_class_prose')
    op.drop_table('move_damage_classes')
    # ### end Alembic commands ###
