"""create pokemon color chape and habitat

Revision ID: 637965b01865
Revises: 7e48c46aaca3
Create Date: 2025-04-23 11:55:59.842852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637965b01865'
down_revision: Union[str, None] = '7e48c46aaca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_habitats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_shapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_color_names',
    sa.Column('pokemon_color_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['pokemon_color_id'], ['pokemon_colors.id'], ),
    sa.PrimaryKeyConstraint('pokemon_color_id', 'local_language_id')
    )
    op.create_table('pokemon_habitat_names',
    sa.Column('pokemon_habitat_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['pokemon_habitat_id'], ['pokemon_habitats.id'], ),
    sa.PrimaryKeyConstraint('pokemon_habitat_id', 'local_language_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_habitat_names')
    op.drop_table('pokemon_color_names')
    op.drop_table('pokemon_shapes')
    op.drop_table('pokemon_habitats')
    op.drop_table('pokemon_colors')
    # ### end Alembic commands ###
