"""create pokemon species

Revision ID: 9e83773309fd
Revises: afa68bbf4bf5
Create Date: 2025-04-23 12:41:01.163669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e83773309fd'
down_revision: Union[str, None] = 'afa68bbf4bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('evolves_from_species_id', sa.Integer(), nullable=True),
    sa.Column('evolution_chain_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('gender_rate', sa.Integer(), nullable=True),
    sa.Column('capture_rate', sa.Integer(), nullable=True),
    sa.Column('base_happiness', sa.Integer(), nullable=True),
    sa.Column('is_baby', sa.Boolean(), nullable=False),
    sa.Column('hatch_counter', sa.Integer(), nullable=False),
    sa.Column('has_gender_differences', sa.Boolean(), nullable=False),
    sa.Column('growth_rate_id', sa.Integer(), nullable=False),
    sa.Column('forms_switchable', sa.Boolean(), nullable=False),
    sa.Column('is_legendary', sa.Boolean(), nullable=False),
    sa.Column('is_mythical', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('conquest_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['pokemon_colors.id'], ),
    sa.ForeignKeyConstraint(['evolution_chain_id'], ['evolution_chains.id'], ),
    sa.ForeignKeyConstraint(['evolves_from_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['growth_rate_id'], ['growth_rates.id'], ),
    sa.ForeignKeyConstraint(['habitat_id'], ['pokemon_habitats.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['pokemon_shapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_species_names',
    sa.Column('pokemon_species_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('genus', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['pokemon_species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('pokemon_species_id', 'local_language_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_species_names')
    op.drop_table('pokemon')
    op.drop_table('pokemon_species')
    # ### end Alembic commands ###
