"""create evolution chain and item

Revision ID: afa68bbf4bf5
Revises: 637965b01865
Create Date: 2025-04-23 12:20:35.321664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa68bbf4bf5'
down_revision: Union[str, None] = '637965b01865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_fling_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('item_pockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pocket_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pocket_id'], ['item_pockets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('item_fling_effect_prose',
    sa.Column('item_fling_effect_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['item_fling_effect_id'], ['item_fling_effects.id'], ),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('item_fling_effect_id', 'local_language_id')
    )
    op.create_table('item_pocket_names',
    sa.Column('item_pocket_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['item_pocket_id'], ['item_pockets.id'], ),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('item_pocket_id', 'local_language_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('fling_power', sa.Integer(), nullable=True),
    sa.Column('fling_effect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['fling_effect_id'], ['item_fling_effects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evolution_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_trigger_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_trigger_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_names',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'local_language_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_names')
    op.drop_table('evolution_chains')
    op.drop_table('items')
    op.drop_table('item_pocket_names')
    op.drop_table('item_fling_effect_prose')
    op.drop_table('item_categories')
    op.drop_table('item_pockets')
    op.drop_table('item_fling_effects')
    # ### end Alembic commands ###
