"""create version

Revision ID: c73a15953d5d
Revises: 55b15f040eed
Create Date: 2025-04-22 21:44:39.082454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73a15953d5d'
down_revision: Union[str, None] = '55b15f040eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    version_groups = op.create_table('version_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    versions = op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_group_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['version_group_id'], ['version_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    version_names = op.create_table('version_names',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'local_language_id')
    )

    from migration.tool import load_csv
    with load_csv("version_groups") as csv_data:
        # id,identifier,generation_id,order
        data = [
            {
                "id": int(row["id"]),
                "identifier": row["identifier"],
                "generation_id": int(row["generation_id"]),
                "order": int(row["order"])
            }
            for row in csv_data
        ]
        op.bulk_insert(version_groups, data)

    with load_csv("versions") as csv_data:
        # id,version_group_id,identifier
        data = [
            {
                "id": int(row["id"]),
                "version_group_id": int(row["version_group_id"]),
                "identifier": row["identifier"]
            }
            for row in csv_data
        ]
        op.bulk_insert(versions, data)

    with load_csv("version_names") as csv_data:
        # version_id,local_language_id,name
        data = [
            {
                "version_id": int(row["version_id"]),
                "local_language_id": int(row["local_language_id"]),
                "name": row["name"]
            }
            for row in csv_data
        ]
        op.bulk_insert(version_names, data)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_names')
    op.drop_table('versions')
    op.drop_table('version_groups')
    # ### end Alembic commands ###
