"""create pokemon stats

Revision ID: f468085379df
Revises: 9e83773309fd
Create Date: 2025-04-23 21:11:58.825508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f468085379df'
down_revision: Union[str, None] = '9e83773309fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_class_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('is_battle_only', sa.Boolean(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['damage_class_id'], ['move_damage_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_names',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('stat_id', 'local_language_id')
    )
    op.create_table('pokemon_stats',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('base_stat', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'stat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_stats')
    op.drop_table('stat_names')
    op.drop_table('stats')
    # ### end Alembic commands ###
