"""create pokemon stats

Revision ID: f468085379df
Revises: 9e83773309fd
Create Date: 2025-04-23 21:11:58.825508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f468085379df'
down_revision: Union[str, None] = '9e83773309fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    stats = op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_class_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('is_battle_only', sa.Boolean(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['damage_class_id'], ['move_damage_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    stat_names = op.create_table('stat_names',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('stat_id', 'local_language_id')
    )
    pokemon_stats = op.create_table('pokemon_stats',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('base_stat', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'stat_id')
    )

    from migration.tool import load_csv

    with load_csv("stats") as csv_data:
        # id,damage_class_id,identifier,is_battle_only,game_index
        data = [
            {
                "id": int(row["id"]),
                "damage_class_id": int(row["damage_class_id"]) if row["damage_class_id"] else None,
                "identifier": row["identifier"],
                "is_battle_only": row["is_battle_only"] == "1",
                "game_index": int(row["game_index"]) if row["game_index"] else None,
            } for row in csv_data
        ]
        op.bulk_insert(stats, data)

    with load_csv("stat_names") as csv_data:
        # stat_id,local_language_id,name
        data = [
            {
                "stat_id": int(row["stat_id"]),
                "local_language_id": int(row["local_language_id"]),
                "name": row["name"],
            } for row in csv_data
        ]
        op.bulk_insert(stat_names, data)

    with load_csv("pokemon_stats") as csv_data:
        # pokemon_id,stat_id,base_stat,effort
        data = [
            {
                "pokemon_id": int(row["pokemon_id"]),
                "stat_id": int(row["stat_id"]),
                "base_stat": int(row["base_stat"]),
                "effort": int(row["effort"]),
            } for row in csv_data
        ]
        op.bulk_insert(pokemon_stats, data)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_stats')
    op.drop_table('stat_names')
    op.drop_table('stats')
    # ### end Alembic commands ###
