"""create growth

Revision ID: 7e48c46aaca3
Revises: 5068fab41598
Create Date: 2025-04-23 11:48:16.151358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e48c46aaca3'
down_revision: Union[str, None] = '5068fab41598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    growth_rates = op.create_table('growth_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('formula', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    growth_rate_prose = op.create_table('growth_rate_prose',
    sa.Column('growth_rate_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['growth_rate_id'], ['growth_rates.id'], ),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('growth_rate_id', 'local_language_id')
    )
    op.bulk_insert(growth_rates, [
        { 'id': 1, 'identifier': 'slow', 'formula': r'\frac{5x^3}{4}' },
        { 'id': 2, 'identifier': 'medium', 'formula': r'x^3' },
        { 'id': 3, 'identifier': 'fast', 'formula': r'\frac{4x^3}{5}' },
        { 'id': 4, 'identifier': 'medium-slow', 'formula': r'\frac{6x^3}{5} - 15x^2 + 100x - 140' },
        { 'id': 5, 'identifier': 'slow-then-very-fast', 'formula': r'\begin{cases} \frac{ x^3 \left( 100 - x \right) }{50},    & \text{if } x \leq 50  \\ \frac{ x^3 \left( 150 - x \right) }{100},   & \text{if } 50 < x \leq 68  \\ \frac{ x^3 \left( 1274 + (x \bmod 3)^2 - 9 (x \bmod 3) - 20 \left\lfloor \frac{x}{3} \right\rfloor \right) }{1000}, & \text{if } 68 < x \leq 98  \\ \frac{ x^3 \left( 160 - x \right) }{100},   & \text{if } x > 98  \\ \end{cases}' },
        { 'id': 6, 'identifier': 'fast-then-very-slow', 'formula': r'\begin{cases} \frac{ x^3 \left( 24 + \left\lfloor \frac{x+1}{3} \right\rfloor \right) }{50},  & \text{if } x \leq 15  \\ \frac{ x^3 \left( 14 + x \right) }{50},     & \text{if } 15 < x \leq 35  \\ \frac{ x^3 \left( 32 + \left\lfloor \frac{x}{2} \right\rfloor \right ) }{50},   & \text{if } x > 35  \\ \end{cases}' }
    ])

    op.bulk_insert(growth_rate_prose, [
        { 'growth_rate_id': 1, 'local_language_id': 5, 'name': 'lente' },
        { 'growth_rate_id': 1, 'local_language_id': 6, 'name': 'langsam' },
        { 'growth_rate_id': 1, 'local_language_id': 9, 'name': 'slow' },
        { 'growth_rate_id': 2, 'local_language_id': 5, 'name': 'moyenne' },
        { 'growth_rate_id': 2, 'local_language_id': 6, 'name': 'mittel' },
        { 'growth_rate_id': 2, 'local_language_id': 9, 'name': 'medium' },
        { 'growth_rate_id': 3, 'local_language_id': 5, 'name': 'rapide' },
        { 'growth_rate_id': 3, 'local_language_id': 6, 'name': 'schnell' },
        { 'growth_rate_id': 3, 'local_language_id': 9, 'name': 'fast' },
        { 'growth_rate_id': 4, 'local_language_id': 5, 'name': 'parabolique' },
        { 'growth_rate_id': 4, 'local_language_id': 6, 'name': 'mittel langsam' },
        { 'growth_rate_id': 4, 'local_language_id': 9, 'name': 'medium slow' },
        { 'growth_rate_id': 5, 'local_language_id': 5, 'name': 'erratique' },
        { 'growth_rate_id': 5, 'local_language_id': 6, 'name': 'langsam, dann sehr schnell' },
        { 'growth_rate_id': 5, 'local_language_id': 9, 'name': 'erratic' },
        { 'growth_rate_id': 6, 'local_language_id': 5, 'name': 'fluctuante' },
        { 'growth_rate_id': 6, 'local_language_id': 6, 'name': 'schnell, dann sehr langsam' },
        { 'growth_rate_id': 6, 'local_language_id': 9, 'name': 'fluctuating' }
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('growth_rate_prose')
    op.drop_table('growth_rates')
    # ### end Alembic commands ###
