"""create pokemon evolution

Revision ID: db557f2347d7
Revises: d8cc0971d5af
Create Date: 2025-04-24 14:27:30.029178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db557f2347d7'
down_revision: Union[str, None] = 'd8cc0971d5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evolution_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('evolution_trigger_prose',
    sa.Column('evolution_trigger_id', sa.Integer(), nullable=False),
    sa.Column('local_language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evolution_trigger_id'], ['evolution_triggers.id'], ),
    sa.ForeignKeyConstraint(['local_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('evolution_trigger_id', 'local_language_id')
    )
    op.create_table('pokemon_evolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evolved_species_id', sa.Integer(), nullable=False),
    sa.Column('evolution_trigger_id', sa.Integer(), nullable=False),
    sa.Column('trigger_item_id', sa.Integer(), nullable=True),
    sa.Column('minimum_level', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('held_item_id', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=10), nullable=True),
    sa.Column('known_move_id', sa.Integer(), nullable=True),
    sa.Column('known_move_type_id', sa.Integer(), nullable=True),
    sa.Column('minimum_happiness', sa.Integer(), nullable=True),
    sa.Column('minimum_beauty', sa.Integer(), nullable=True),
    sa.Column('minimum_affection', sa.Integer(), nullable=True),
    sa.Column('relative_physical_stats', sa.Integer(), nullable=True),
    sa.Column('party_species_id', sa.Integer(), nullable=True),
    sa.Column('party_type_id', sa.Integer(), nullable=True),
    sa.Column('trade_species_id', sa.Integer(), nullable=True),
    sa.Column('needs_overworld_rain', sa.Boolean(), nullable=True),
    sa.Column('turn_upside_down', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evolution_trigger_id'], ['evolution_triggers.id'], ),
    sa.ForeignKeyConstraint(['evolved_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['held_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['party_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['party_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['trade_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['trigger_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_evolution')
    op.drop_table('evolution_trigger_prose')
    op.drop_table('evolution_triggers')
    # ### end Alembic commands ###
